// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlvXfo3nOlLFRouOnIQE74oLEldy4ccaI',
    appId: '1:799242442843:web:aaa4656c5c225dbb26877e',
    messagingSenderId: '799242442843',
    projectId: 'task-sync-pro-v2-b52e9',
    authDomain: 'task-sync-pro-v2-b52e9.firebaseapp.com',
    storageBucket: 'task-sync-pro-v2-b52e9.appspot.com',
    measurementId: 'G-0JDBFMBJ8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6HC6u4z36o6qd6Job9uoCxVg9gcXUp6k',
    appId: '1:799242442843:android:0fed9154584dc8bf26877e',
    messagingSenderId: '799242442843',
    projectId: 'task-sync-pro-v2-b52e9',
    storageBucket: 'task-sync-pro-v2-b52e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLV_FfNC0owefHxTXJzp7U2_jIm4rQukI',
    appId: '1:799242442843:ios:7bf88ec31da5e91026877e',
    messagingSenderId: '799242442843',
    projectId: 'task-sync-pro-v2-b52e9',
    storageBucket: 'task-sync-pro-v2-b52e9.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLV_FfNC0owefHxTXJzp7U2_jIm4rQukI',
    appId: '1:799242442843:ios:6e19704108a181d826877e',
    messagingSenderId: '799242442843',
    projectId: 'task-sync-pro-v2-b52e9',
    storageBucket: 'task-sync-pro-v2-b52e9.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
